Upload project
stepancar-web-programming/2023-fall-lab-portfolio-parfenova-o.-s. pull request #1
Opened 2023-11-17 11:41 UTC by emshen6

2023-12-06 23:05 UTC, stepancar commented on package.json
> +    "@testing-library/jest-dom": "^5.17.0",
Давайте вспомним про вопрос рубежки, разница между dependency / devDependency

2023-12-06 23:08 UTC, stepancar commented on src/components/btnExpand/BtnExpand.js
> +      isComponentVisible === true ? false : true
```suggestion
      !isComponentVisible
```
Согласитесь, так короче?
Скорее всего, eslint вам бы такое подсказал. давайте его подключим.

2023-12-06 23:13 UTC, stepancar commented on src/components/project/Project.js
> +      <li className="project">
Обратите внимание что возможно это не лучшая композиция. Этот компонент создан для того чтобы отображать информацию о проекте, верно? Предполагается (не всегда) что компонент это какая-то переиспользуемая сущность. Однако при такой верстке такой компонент можно вставить только во внутрь `ul`

2023-12-06 23:17 UTC, stepancar commented on src/pages/ProjectPage.js
> +              src={project.imgBig}
Давайте используем https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

2023-12-06 23:18 UTC, stepancar commented on public/manifest.json
> +      "src": "logo512.png",
Давайте сделаем свои иконки

2023-12-06 23:22 UTC, stepancar commented on src/components/btnExpand/BtnExpand.js
> +    }, 30);
Давайте представим что у нас на странице анимируется множество объектов таким методом. 
Это не всегда будет работать плавно, так как main thread может быть занят другими задачами. Важно стараться делать анимации на css там где это возможно. Давайте сделаем!

2023-12-06 23:22 UTC, stepancar requested changes
Нужно сделать анимации на сss + мелкие замечания

2024-01-18 09:37 UTC, stepancar commented on src/components/btnDarkMode/BtnDarkMode.js
> +    console.log("toggle dark mode");
```suggestion
```

2024-01-18 09:39 UTC, stepancar commented on src/components/navbar/Navbar.js
> +  const activeLink = "nav-list__link nav-list__link--active";
одна из популярных утилит для решения этой задачи https://www.npmjs.com/package/classnames

2024-01-18 09:43 UTC, stepancar commented on src/pages/Contacts.js
> +            <p>parfenovao752@gmail.com</p>
Давайте сделаем чтобы при нажатии открывался почтовый клиент

2024-01-18 09:44 UTC, stepancar commented on package.json
> +    "react-scripts": "5.0.1",
react-scripts - devDependency

2024-01-18 09:45 UTC, stepancar commented on src/components/btnExpand/style.css
> +.skill-box .skill-bar{
Пожалуйста, приведите код к единому форматированию. Используйте автоматические средства для форматирования

2024-01-18 09:51 UTC, stepancar commented on src/components/btnDarkMode/BtnDarkMode.js
> +      .addEventListener("change", (event) => {
Давайте корректно обработаем ситуацию, когда экземпляр компонента удаляется

2024-01-19 07:32 UTC, stepancar commented on src/pages/Home.js
> +                  key={index}
Пожалуйста, изучите вопрос к экзамены,почему это не всегда хорошо

2024-01-19 07:37 UTC, stepancar requested changes
Демо по приложенной ссылке не соответствует тому, что я вижу в вашей ветке.
Например <a href="mailto:parfenovao752@gmail.com">parfenovao752@gmail.com</a>
там сделано тегом p

2024-01-19 07:43 UTC, stepancar commented on src/components/btnDarkMode/BtnDarkMode.js
> +    </button>
обратите внимание, при клавиатурной навигации кнопка не выделяется как это происходит с обычными элементами.

2024-01-21 07:46 UTC, emshen6 commented on src/pages/Home.js
> +                  key={index}
Если порядок элементов в массиве может изменяться (например, при добавлении, удалении или изменении порядка), использование индекса в качестве ключа может привести к проблемам. При изменении порядка элементов React может потерять соответствие между элементами и их ключами, что может привести к неожиданному поведению или перерендерингу компонентов.

2024-01-21 08:59 UTC, emshen6 commented
> Демо по приложенной ссылке не соответствует тому, что я вижу в вашей ветке. Например [parfenovao752@gmail.com](mailto:parfenovao752@gmail.com) там сделано тегом p

билд исправлен

2024-01-21 10:11 UTC, stepancar commented on src/utils/scrollToTop.js
> +  return null;
для чего нужно возвращать значение если всегда возвращается null?

2024-01-21 10:14 UTC, stepancar commented on src/pages/Projects.js
> +                key={index}
если бы вы добавили в проект eslint https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md
мне бы не пришлось оставлять комментарии вам

2024-01-21 10:19 UTC, stepancar commented on README.md
> +https://emshen.netlify.app/
Если перейти на вкладку projects, перезагрузить страницу - появляется сообщение:
<img width="850" alt="Screenshot 2024-01-21 at 2 19 32 AM" src="https://github.com/stepancar-web-programming/2023-fall-lab-portfolio-parfenova-o.-s./assets/2854910/51f95260-ef91-4015-8ecb-90765aa96fc7">

2024-01-21 10:22 UTC, stepancar commented on src/components/btnGitHub/style.css
Пустой файл

2024-01-21 10:23 UTC, stepancar commented on src/components/btnGitHub/BtnGitHub.js
> +      <img src={gitHubIcon} alt="" />
```suggestion
      <img src={gitHubIcon} alt="github icon" />
```

2024-01-21 10:26 UTC, stepancar commented on public/manifest.json
> +  "name": "Create React App Sample",
?

2024-01-21 10:30 UTC, stepancar commented on src/components/btnHabr/BtnHabr.js
> +      <img src={habrIcon} alt="" />
?

2024-01-21 20:30 UTC, stepancar approved these changes

2024-01-21 20:31 UTC, merged